import './globals.css'
import {heebo} from '../analytics/font/fonts';
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export const metadata = {
  title: 'Restuarant',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={heebo.className}>
      <head/>
      <body>{children}</body>
    </html>
  )
}
